#INCLUDE <P16F628A.INC>		;ARQUIVO PADRÃO MICROCHIP PARA 16F628A
RADIX DEC
__CONFIG H'3F10'

	CBLOCK	0x20	;ENDEREÇO INICIAL DA MEMÓRIA DE USUÁRIO
	CONTADOR1
	CONTADOR2
	CONTADOR3
	ENDC			;FIM DO BLOCO DE MEMÓRIA		

#DEFINE	BOTAO	PORTA,2	;PORTA DO BOTÃO
					; 0 -> PRESSIONADO
					; 1 -> LIBERADO

#DEFINE	LED1	PORTB,0	;PORTA DO LED 0 -> APAGADO 1 -> ACESO
#DEFINE	LED2	PORTB,1	;PORTA DO LED 0 -> APAGADO 1 -> ACESO
#DEFINE	LED3	PORTB,2	;PORTA DO LED 0 -> APAGADO 1 -> ACESO
#DEFINE	LED4	PORTB,3	;PORTA DO LED 0 -> APAGADO 1 -> ACESO
#DEFINE	LED5	PORTB,4	;PORTA DO LED 0 -> APAGADO 1 -> ACESO
#DEFINE	LED6	PORTB,5 ;PORTA DO LED 0 -> APAGADO 1 -> ACESO

	ORG	0x00		;ENDEREÇO INICIAL DE PROCESSAMENTO
	GOTO	INICIO
	
INICIO
	CLRF	PORTA		;LIMPA O PORTA
	CLRF	PORTB		;LIMPA O PORTB
	BSF STATUS, RP0			;ALTERA PARA O BANCO 1
	MOVLW	B'00000100'
	MOVWF	TRISA		;DEFINE RA2 COMO ENTRADA E DEMAIS COMO SAÍDAS
	CLRF	TRISB		;DEFINE TODO O PORTB COMO SAÍDA
	CLRF	INTCON		;TODAS AS INTERRUPÇÕES DESLIGADAS	
	BCF STATUS, RP0 ;RETORNA PARA O BANCO 0
	MOVLW	B'00000111'
	MOVWF	CMCON		;DEFINE O MODO DO COMPARADOR ANALÓGICO

MAIN
	CALL TIMEOUT
	GOTO MAIN
	
	TIMEOUT
		
		MOVLW 6
		MOVWF CONTADOR1
		
		ATRASO1
		
			MOVLW 1
			MOVFW CONTADOR2
				
				ATRASO2
				
					MOVLW 1
					MOVFW CONTADOR3
						
					ATRASO3
						DECFSZ CONTADOR3
						GOTO ATRASO3
							
				DECFSZ CONTADOR2
				GOTO ATRASO2
		
		DECFSZ CONTADOR1
		GOTO ATRASO1

	RETURN 
	
	

	END			;OBRIGATÓRIO


